### PR TITLE
Fixes #624 - Updated Appdata/roaming

### LINKED ISSUE #624: Readme is \%appdata%\Roaming rather than \%appdata%\
## What is the bug?
`\%appdata%\` is the path `C:\Users\USERNAME\AppData\Roaming` therefore `\%appdata%\Roaming` is `C:\Users\USERNAME\AppData\Roaming\Roaming` which is invalid by default.

## How to reproduce?
```
Steps to reproduce the behavior:
1. Attempt to navigate to `\%appdata%\Roaming` from a file explorer.
2. Note error
3. Attempt to navigate to `\%appdata%\` 
4. Note you navigate to `C:\Users\USERNAME\AppData\Roaming` 
```

This can be confusing for new users to follow. Simple workaround but equally simple to fix in the documentation.

### PR DESCRIPTION
**Pull request by Brett-Parker**
Fixes #624 

# Summary of changes

\%appdata%\ is the path C:\Users\USERNAME\AppData\Roaming therefore \%appdata%\Roaming is C:\Users\USERNAME\AppData\Roaming\Roaming which is invalid by default.

### CODE REVIEW

**Comment by Brett-Parker** [comment]
As described. Updated ChangeLog however, not sure of next release, 2024/TBD put for now. Assumed to be updated closer to the time.

**Comment by Brett-Parker** [comment]
Ready for review.

**Comment by PaulWalkerUK** [comment]
The leading "\" should really be removed as well, so `%appdata%\EuroScope` instead of `\%appdata%\EuroScope`

**Comment by Brett-Parker** [comment]
> The leading `\` should really be removed as well, so `%appdata%\EuroScope` instead of `\%appdata%\EuroScope`

Can remove both are acceptable with or without work. I left it in as it was there previously.

**Comment by PaulWalkerUK** [comment]
The leading `\` might work(/be ignored) in some places but it isn't valid and doesn't work everywhere. As you say, `APPDATA` is an environment variable that has the value `C:\Users\<name>\AppData\Roaming`. Therefore:
-  `%APPDATA%\EuroScope` is `C:\Users\<name>\AppData\Roaming\EuroScope` (valid)
- `\%APPDATA%\EuroScope` is `\C:\Users\<name>\AppData\Roaming\EuroScope` (invalid)

Eg from a cmd prompt:

```
C:\>cd %APPDATA%\EuroScope

C:\Users\Paul\AppData\Roaming\EuroScope>
```

Whereas:
```
C:\>cd \%APPDATA%\EuroScope
The filename, directory name, or volume label syntax is incorrect.
```


I could also make a case that the environment variable name `APPDATA` is and should really be written in uppercase, but Windows isn't case-sensitive in this regard so it doesn't make a difference. Listing the environment variables from a cmd prompt:

```
C:\>set
ACSvcPort=17532
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Paul\AppData\Roaming
...
...
```

**Comment by Brett-Parker** [comment]
> The leading `\` might work(/be ignored) in some places but it isn't valid and doesn't work everywhere. As you say, `APPDATA` is an environment variable that has the value `C:\Users\<name>\AppData\Roaming`. Therefore:
> 
> * `%APPDATA%\EuroScope` is `C:\Users\<name>\AppData\Roaming\EuroScope` (valid)
> * `\%APPDATA%\EuroScope` is `\C:\Users\<name>\AppData\Roaming\EuroScope` (invalid)
> 
> Eg from a cmd prompt:
> 
> ```
> C:\>cd %APPDATA%\EuroScope
> 
> C:\Users\Paul\AppData\Roaming\EuroScope>
> ```
> 
> Whereas:
> 
> ```
> C:\>cd \%APPDATA%\EuroScope
> The filename, directory name, or volume label syntax is incorrect.
> ```
> 
> I could also make a case that the environment variable name `APPDATA` is and should really be written in uppercase, but Windows isn't case-sensitive in this regard so it doesn't make a difference. Listing the environment variables from a cmd prompt:
> 
> ```
> C:\>set
> ACSvcPort=17532
> ALLUSERSPROFILE=C:\ProgramData
> APPDATA=C:\Users\Paul\AppData\Roaming
> ...
> ...
> ```
> 
> (By the way, thank you for submitting this PR - I spotted the issue in the instructions as well, but never got around to trying to fix it! 🙂)

Agree with all, I think to ensure inclusivity for all I have I removed the leading / and also changed appdata to APPDATA for consistency...

Committ [4861b7f](https://github.com/VATSIM-UK/uk-controller-pack/pull/625/commits/4861b7f37dcc03056fcc09624766372659e2a9cb)
Merge state
Add more commits by pushing to the [Issue-624](https://github.com/Brett-Parker/uk-controller-pack/tree/Issue-624) branch on [Brett-Parker/uk-controller-pack](https://github.com/Brett-Parker/uk-controller-pack).

Review required
At least 1 approving review is required by reviewers with write access. 
Merging is blocked
Merging can be performed automatically with 1 approving review.
 You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.
@Brett-Parker


Add a comment
Comment
> The leading `\` might work(/be ignored) in some places but it isn't valid and doesn't work everywhere. As you say, `APPDATA` is an environment variable that has the value `C:\Users\<name>\AppData\Roaming`. Therefore:
> 
> * `%APPDATA%\EuroScope` is `C:\Users\<name>\AppData\Roaming\EuroScope` (valid)
> * `\%APPDATA%\EuroScope` is `\C:\Users\<name>\AppData\Roaming\EuroScope` (invalid)
> 
> Eg from a cmd prompt:
> 
> ```
> C:\>cd %APPDATA%\EuroScope
> 
> C:\Users\Paul\AppData\Roaming\EuroScope>
> ```
> 
> Whereas:
> 
> ```
> C:\>cd \%APPDATA%\EuroScope
> The filename, directory name, or volume label syntax is incorrect.
> ```
> 
> I could also make a case that the environment variable name `APPDATA` is and should really be written in uppercase, but Windows isn't case-sensitive in this regard so it doesn't make a difference. Listing the environment variables from a cmd prompt:
> 
> ```
> C:\>set
> ACSvcPort=17532
> ALLUSERSPROFILE=C:\ProgramData
> APPDATA=C:\Users\Paul\AppData\Roaming
> ...
> ...
> ```
> 
> (By the way, thank you for submitting this PR - I spotted the issue in the instructions as well, but never got around to trying to fix it! 🙂)

Agree with everything, I think to ensure inclusivity for all I have I removed the leading \ and also changed appdata to APPDATA for consistency...

**Comment by PaulWalkerUK** [comment]
One very minor last thing (sorry!) - a couple of spaces seem to have crept into the path in the install section where it says about checking for `% APPDATA %\EuroScope\UK\Essex\Stansted SMR.prf`

**Comment by Brett-Parker** [comment]
> One very minor last thing (sorry!) - a couple of spaces seem to have crept into the path in the install section where it says about checking for `% APPDATA %\EuroScope\UK\Essex\Stansted SMR.prf`

Don't apologise, that is what PR reviews are for. Not sure how they crept in - removed either side of APPDATA . I checked 'Stansted SMR.prf', space is expected there.

**Comment by PaulWalkerUK** [comment]
That's got it, looking good to me 🙂

**Review by luke11brown — APPROVED** [review]

**Pull request merged**
