### PR TITLE
Fixes #818 - Added VRPs to TopSky maps

### LINKED ISSUE #818: Add VRPs to TopSkyMaps
## What is the current situation?
Need to draw VRPs on displays when required. ES freetext does not display this realistically.

## What is the proposed change?
Add VRPs to display in TopSky.

## Reference materials (e.g. screenshots)
brave_ql2iFXjvO9
brave_L5mxpUaNh7

### PR DESCRIPTION
**Pull request by SamLefevre**
Fixes #818 

# Summary of changes

Added TopSky maps with auto activation if radar display usually has symbols real world and has an option for labels as well.

# Screenshots (if necessary)

image
image

### CODE REVIEW

**Comment by SamLefevre** [comment]
Should we use TopSkyMapsLocal.txt for things when we **don't** want them to match?

**Comment by SamLefevre** [comment]
TopSkyMapsLocal adds everything into a LMAPS folder that's in there even if a folder is defined. Nevermind!

**Comment by luke11brown** [comment]
So. for clarity you'll have to run me through the Maps.txt.

Most seem to have no activation lines?

I recall a conversation about using Alt+V to turn on?

**Comment by SamLefevre** [comment]
In TopSkySettings.txt:

```
Shortcut_Map_Xfr_Key=2,0x56 ; V
Shortcut_Map_Target=5,VRPs
```

**Comment by SamLefevre** [comment]
Based on what RW displays had, a lot don't have the symbols displayed by default, although EGGP, EGGD, etc we want them displayed when someone logs on to the position.

**Pull request merged**
