### PR TITLE
Profiles: Add TopSky to non-TopSky profiles

### LINKED ISSUE #483: Non-Topsky Profiles and update history trails
Change current non-topsky profiles to keep default settings but have TopSky enabled for automatic airspace activation and other features.

Trails should also be yellow.

### LINKED ISSUE #525: Logon Details: VCCS username not insterted
## What is the bug?
VCCS username not inserted. 

PrfVCCS not in write section

## How to reproduce?
Run Logon Details exe

### PR DESCRIPTION
**Pull request by luke11brown**
Fixes #483 
Fixes #525 

# Summary of changes

Adds TopSky to non-TopSky LTC ,STC, MPC and area profiles for automatic airspace activation, whilst retaining default tag functions.

Issues to fix as below.

# Screenshots (if necessary)

To follow

### CODE REVIEW

**Comment by luke11brown** [comment]
To fix
image

**Comment by luke11brown** [comment]
Only a single Symbols file is possible :(

**Comment by SamLefevre** [comment]
Might need to have 1 TopSky folder for AC and 1 for TC. For TC I suggest for zooms we initally have our tickless centerlines but then zooming in the ticks appear, I'm adding tickless centerlines to the select file. Issue with this however would be obviously adding the functionality but also maintaining to TopSkys.

**Comment by luke11brown** [comment]
Just had a thought. Maybe we can redirect the settings files if we use the same syntax as https://github.com/VATSIM-UK/uk-controller-pack/blob/main/UK/Data/Plugin/TopSky/ICAO_Aircraft.txt

Will require testing to see if it works the same way.

If so, then I suggest we can put a sub folder with another TopSky DLL. The only file that will need to be different is the radar one.

**Comment by luke11brown** [comment]
> Just had a thought. Maybe we can redirect the settings files if we use the same syntax as https://github.com/VATSIM-UK/uk-controller-pack/blob/main/UK/Data/Plugin/TopSky/ICAO_Aircraft.txt
>
> Will require testing to see if it works the same way.

Does not work

image

**Pull request closed without merging**
