### PR TITLE
Fixes #412 - Add ECFMP CDM Plugin

### LINKED ISSUE #412: Incorporate CDM plugin
## What is the current situation?
No CDM Plugin

## What is the proposed change?
Include CDM plugin from https://github.com/rpuig2001/CDM

## Reference materials (e.g. screenshots)
https://github.com/rpuig2001/CDM

## Additional context
Median taxi times available from https://www.eurocontrol.int/publication/taxi-times-summer-2022

### PR DESCRIPTION
**Pull request by luke11brown**
Fixes #412 

# Summary of changes

Adds CDM plugin from https://github.com/vACDM
- Plugin added

To do
- [x] Create Taxi zones for different airfields based on https://www.eurocontrol.int/performance/data/download/xls/Taxi_times_Planning_Data_S14_S22.xlsx (could also be done per area/terminal/runway if desired
- [x] Create UK CAD text file and host on GitHub (once complete, get https://raw.githubusercontent.com/rpuig2001/Capacity-Availability-Document-CDM/main/CAD.txt to point to UK file)
- [x] Modify rate.txt to hold dep rate info
- [x]  Rate file to be hosted on this GitHub, XML to point at this file
- [x] Decide on colour schema

# Screenshots (if necessary)

< Please provide screenshots if this will facilitate a faster review of these changes >

### CODE REVIEW

**Comment by luke11brown** [comment]
Provisional dep rates:
EGBB,22
EGCC,SRO 26, Duals 33
EGFF,22
EGGD,22
EGGP,22
EGGW,RW07 23, RW25, 22
EGHH,15
EGHI,15
EGJB,20
EGJJ,20
EGKK,26
EGLC,22
EGLL,SRO 26, duals, 40
EGNX,22
EGPD,20
EGPF,22
EGPH,22
EGSS,25

**Comment by luke11brown** [comment]
Provisional taxi zones
EGBB
12 (33) 15(15)
EGCC
T2(north of NC2) 20(23R) 20(05L) 22(23L)
T1(Pier B&C) 16(23R/05L) 18(23L)
T3 14(23R) 18(05L) 16(23L)

EGFF,22
EGGD,22
EGGP,22
EGGW,RW07 23, RW25, 22
EGHH,15
EGHI,15
EGJB,20
EGJJ,20
EGKK,26
EGLC,22
EGLL,SRO 26, duals, 40
EGNX,22
EGPD,20
EGPF,22
EGPH,22
EGSS,25

**Comment by luke11brown** [comment]
This is now ready, except the decision of which items/actions we need to include in departure lists.
Items available (L/R click actions in brackets):
- EOBT (aEOBT options and edit EOBT suggest L/R click respectively)
- E (unsure of the function of this)
- TOBT (TOBT options, ready TOBT and edit TOBT)
- TSAT
- TTOT
- TSAC (TSAC actions, add TSAT to TSAC, Edit TSAC)
- ASAT
- ASRT (Toggle ASRT)
- CTOT (CTOT Options, CTOT Option List)
- Ready start up (Toggle Ready start up)

All CDM options click action also available

@hazzas-99 Thoughts on what is useful here?

**Comment by luke11brown** [comment]
Calling @cbyworth to the stand

**Comment by cbyworth** [comment]
I'll try and take a look at this over the bank holiday 👍

**Comment by cbyworth** [comment]
I haven't yet had a chance to properly think about this.

However, throwing a potential spanner into the works.
I was asked the other week about this: 
https://vacdm-dev.vatsim-germany.org/
Which includes an API with a web-hosted VDGS and apparently some plans to integrate with GS/Aerosoft....

image

Probably need @KHardern and @AndyTWF input as well. I gather both this CDM and the VATGER VACDM also integrate/plan to integrate with ECFMP MDIs etc?

**Comment by luke11brown** [comment]
@CalumTowers or @AndyTWF Looks like the VATGER based solution is more feature rich. Docs are here https://vacdm.net/docs/developer-guide/installation

Something about a docker instance and I lost interest. Is this something we can look to implement? This could prove useful in events such as CTP. 

@hazzas-99 I suggest at the same time as this we look to utilise the new lists in EuroScope to only display relevant times in the various lists and removing just the "departure" list, giving vanilla ES a more vstrips-esque display to GND/DEL controllers.

**Comment by luke11brown** [comment]
To do:

- Add VATCAN and CDM plugins to profiles

**Review by fcooper94 — APPROVED** [review]
All looks good to me. Good stuff

**Comment by luke11brown** [comment]
@hsugden - there is a small issue with the vACDM plugin.

When initially loading it looks at all the runways selected on the right two columns of the selection dialog to determine active runways in use. As we set these via the RWY file supplied, this leads to an extended loading time. I believe the reason we include a RWY file with the sector file is to ensure runway dependent agreements/COPs are shown? Is that correct?

It loads eventually, but it takes around 30 seconds. Non-issue of no runways are selected on the right side.

**Pull request merged**
