### PR TITLE
Fixes #751 - Use TopSky on TC/APP Displays

### LINKED ISSUE #751: Use TopSky on TC/APP Displays
## What is the current situation?
TopSky only used on area profiles

## What is the proposed change?
Approach & TC profiles/displays to use TopSky at the minimum to display part time airspace and danger area activations, other features can be omitted. Tag functionalities such as auto text (on heading assign for example) will therefore be retained.

- [x] Symbols to be disabled (this seems to be the problem, possiblity of using native ES radar track symbols for all)
- [ ] Colours to be changed (see below solution for login callsign based settings)
- [ ] TopSky lines in ASRs require setting up
- [ ] non-TopSky area profiles can have TopSky enabled but retain the tag family

## Reference materials (e.g. screenshots)
image
image

### PR DESCRIPTION
**Pull request by luke11brown**
Fixes #751

# Summary of changes

- Adds further instances of TopSky & its' associated datafiles based on equipment used/position
- Adds GitHub workflow to ensure matches between certain TopSky datafiles that should match between all instances
- Each TopSky instance defines colours in the TopSkySettings.txt file, rather than in TopSkyMaps.txt
- Oxford & Military excluded

# Screenshots (if necessary)

WIP

### CODE REVIEW

**Comment by luke11brown** [comment]
action currently fails on TopSkyMaps.txt

colordefs to be moved to TopSkySettings.txt a la:

COLORDEF lines in TopSkyMaps.txt and TopSkyAreas.txt to be amended to one of the changeable defintions. e.g. Grey becomes:
`Color_Active_Map_Type_1` This can then be changed using the SettingsLocal file 
based on login callsign.
Note: `Color_Active_Map_Type_1` is currently used for all danger areas.

currently defined in TopSkyMaps.txt
```
COLORDEF:Grey:80:80:80
COLORDEF:Freetext:65:65:65
COLORDEF:Red:120:0:0
COLORDEF:Line:120:120:120
COLORDEF:Centreline:75:75:75
COLORDEF:OCAS:55:55:57
COLORDEF:CAS:28:28:28
COLORDEF:Fix:140:140:140
```

Becomes defined in TopSkySettingsLocal.txt
```
//Danger area (red)
Color_Active_Map_Type_1=120,120,120
//ARTCC High (Grey on NERC)
Color_Active_Map_Type_2=80,80,80
//Freetext
Color_Active_Map_Type_3=65,65,65
//STARs (RMA Lines)
Color_Active_Map_Type_4=120,0,0
//Centrelines
Color_Active_Map_Type_5=75,75,75
//OCAS infill
Color_Active_Map_Type_6=55,55,57
//Sector background infill
Color_Active_Map_Type_7=28,28,28
//Fixes
Color_Active_Map_Type_8=140,140,140
```

**Comment by luke11brown** [comment]
NODE:
Change colors for returns
image
Add TopSky dummy items to tags

NOVA:
set up symbols
Change colors for returns
Add TopSky dummy items to tags
Investigate SettingsLocal for differences such as Edinburgh

**Comment by luke11brown** [comment]
NODE:

Non concerened:
image

Predicted in:
image


Thoughts? @SamLefevre

**Comment by SamLefevre** [comment]
I think non-concerned grey, concerned yellow, assumed green, redundant darker green

**Comment by luke11brown** [comment]
**Local Differences (Symbology)**

Belfast
- [ ] Active Map 1-7 TopSky colours

Birmingham
- [ ] Active Map 1-7 TopSky colours

Bristol
- [ ] Active Map 1-7 TopSky colours

Cardiff
- [ ] Active Map 1-7 TopSky colours

East Midlands
- [ ] Active Map 1-7 TopSky colours

Edinburgh
- [ ] Active Map 1-7 TopSky colours
- [ ] Disable TopSky FAVA? Or change colour?

Exeter
- [ ] Active Map 1-7 TopSky colours

Glasgow
- [ ] Active Map 1-7 TopSky colours

Leeds
- [ ] Active Map 1-7 TopSky colours

Liverpool
- [ ] Active Map 1-7 TopSky colours

Manchester
- [ ] Active Map 1-7 TopSky colours
- [ ] Disable SCT RMA on ASRs

Newcastle
- [ ] Active Map 1-7 TopSky colours

Solent
- [ ] Same as Glasgow

Southend
- [ ] Active Map 1-7 TopSky colours

**Noticed Issues**
- [ ] 1. Cardiff still shows Portsmouth CTA conditional ploygon?
- [ ] 2. Bristol, Cardiff, Edinburgh, Exeter, Leeds still show default extended centrelines, maybe disable the TopSky ones on NOVA?
- [ ] 3. Maybe add ASRDATA:RMA to disable RMAs on certain displays e.eg some APP untis like Leeds, Liverpool (also then have to add RMA to any ASR that has ShowMapData line
- [ ] 4. Did I forget Oxford completely?

**Comment by luke11brown** [comment]
.dcenter TopSky settings

**Comment by luke11brown** [comment]
> I think non-concerned grey, concerned yellow, assumed green, redundant darker green

I think maybe pink for coordination a la
image

**Pull request merged**
